// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rmkwryyzpaofdoykkycd.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJta3dyeXl6cGFvZmRveWtreWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEyNTQ3NTUsImV4cCI6MjA0NjgzMDc1NX0.sPMZk1v0l4lgukdI2e7AEQoyWfSGHME8qoSmJuv87a8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);